[package]
name = "cfront"
version = "0.1.3"
edition = "2021"
description = "A token analyzer for C language"
license = "MIT" 
repository = "https://github.com/CutieDeng/cfront-rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
